import { Text, View } from "@react-pdf/renderer";
import type { PublicFeeSchedule } from "@/lib/services/fee-data";
import { formatDate } from "@/lib/dates";
import { BOARDING_LABEL } from "@/lib/services/fee-data";
import { C, pdfMoney, s, SchoolDoc } from "./theme";

/** Fee structure PDF, generated from exactly the same data as the fee web pages. */
export function FeeSchedulePdf({ schedule }: { schedule: PublicFeeSchedule }) {
  return (
    <SchoolDoc
      title={`Fee structure ${schedule.year.name}`}
      subtitle={schedule.boarding.map((b) => BOARDING_LABEL[b]).join(" · ")}
    >
      <Text style={[s.p, s.muted]}>
        All amounts are per year unless marked one-time. Figures are sample placeholders generated by the fee
        engine.
      </Text>
      {schedule.bands.map((band) => {
        const codes = [...new Map(band.columns.flatMap((c) => c.lines).map((l) => [l.code, l])).values()];
        return (
          <View key={band.band} wrap={false}>
            <Text style={s.h2}>
              {band.label} <Text style={s.small}>({band.years})</Text>
            </Text>
            <View style={s.row}>
              <Text style={[s.th, { flex: 2 }]}>Fee</Text>
              {band.columns.map((c) => (
                <Text key={c.boarding} style={[s.th, s.right, { flex: 1 }]}>
                  {BOARDING_LABEL[c.boarding]}
                </Text>
              ))}
            </View>
            {codes.map((line) => (
              <View key={line.code} style={s.row}>
                <Text style={{ flex: 2 }}>
                  {line.name}
                  <Text style={s.small}>
                    {line.oneTime ? "  one-time" : ""}
                    {line.refundable ? "" : "  non-refundable"}
                  </Text>
                </Text>
                {band.columns.map((c) => {
                  const l = c.lines.find((x) => x.code === line.code);
                  return (
                    <Text key={c.boarding} style={[s.right, { flex: 1 }]}>
                      {l ? pdfMoney(l.amountPaise) : "—"}
                    </Text>
                  );
                })}
              </View>
            ))}
            <View style={[s.row, { backgroundColor: C.cream }]}>
              <Text style={[s.bold, { flex: 2, paddingLeft: 2 }]}>First year, new pupils</Text>
              {band.columns.map((c) => (
                <Text key={c.boarding} style={[s.bold, s.right, { flex: 1 }]}>
                  {pdfMoney(c.firstYearPaise)}
                </Text>
              ))}
            </View>
            <View style={{ flexDirection: "row", marginTop: 6 }}>
              {band.columns.map((c) => (
                <View key={c.boarding} style={{ flex: 1, marginRight: 8 }}>
                  <Text style={[s.small, s.bold]}>{BOARDING_LABEL[c.boarding]} · three instalments</Text>
                  {(c.plans.THREE ?? Object.values(c.plans)[0])!.instalments.map((i) => (
                    <Text key={i.label} style={s.small}>
                      {i.label} (due {formatDate(i.dueDate, "d MMM yyyy")}): {pdfMoney(i.amountPaise)}
                    </Text>
                  ))}
                </View>
              ))}
            </View>
          </View>
        );
      })}
      <View wrap={false}>
        <Text style={s.h2}>Policies</Text>
        <Text style={s.p}>
          Registration fee {pdfMoney(schedule.bands[0]?.columns[0]?.registrationPaise ?? 0)}, payable online
          at registration, non-refundable.
        </Text>
        {schedule.rebate && (
          <Text style={s.p}>
            Advance payment rebate: {pdfMoney(schedule.rebate.amountPaise)} when the year is paid in full by{" "}
            {formatDate(schedule.rebate.payByDate, "d MMMM yyyy")}.
          </Text>
        )}
        {schedule.lateFee && (
          <Text style={s.p}>
            Late fee: {schedule.lateFee.ratePerMonthBp / 100}% per month on overdue amounts after{" "}
            {schedule.lateFee.graceDays} days&apos; grace.
          </Text>
        )}
        <Text style={s.p}>
          Concessions: {schedule.concessions.map((c) => c.name).join("; ")}. Applied in a fixed order; some
          cannot be combined.
        </Text>
        <Text style={s.p}>
          Withdrawal: new pupils receive {schedule.refundPolicy.newPupil.beforeStartBp / 100}% of refundable
          fees if withdrawn before the session starts. Existing pupils give{" "}
          {schedule.refundPolicy.existingPupil.noticeDays} days&apos; notice; refundable fees for the unused
          part of the year are refunded pro rata.
        </Text>
        <Text style={s.p}>
          Imprest per term:{" "}
          {schedule.imprest
            .map((i) => `${BOARDING_LABEL[i.boarding]} ${pdfMoney(i.amountPerTermPaise)}`)
            .join(" · ")}
          .
        </Text>
      </View>
    </SchoolDoc>
  );
}
