/** 301 redirect map for aliases and legacy-style URLs. Also documented in docs/CONTENT_GUIDE.md. */
type Redirect = { source: string; destination: string; statusCode: 301 };

const map: [string, string][] = [
  ["/about", "/about/welcome"],
  ["/about-us", "/about/welcome"],
  ["/welcome", "/about/welcome"],
  ["/history", "/about/our-story"],
  ["/about/history", "/about/our-story"],
  ["/about/awards", "/about/recognition"],
  ["/about/faculty", "/faculty"],
  ["/about/alumni", "/about/alumnae"],
  ["/mission", "/about/mission-and-vision"],
  ["/academics", "/academics/curriculum"],
  ["/academic", "/academics/curriculum"],
  ["/academics/upper", "/academics/upper-school"],
  ["/academics/sixthform", "/academics/sixth-form"],
  ["/admissions/joining", "/admissions"],
  ["/admissions/process", "/admissions"],
  ["/admissions/fees", "/admissions/fees/full-boarding"],
  ["/admissions/scholarship", "/admissions/scholarships"],
  ["/fees", "/admissions/fees/full-boarding"],
  ["/fees/day-boarding", "/admissions/fees/day-boarding"],
  ["/fees/full-boarding", "/admissions/fees/full-boarding"],
  ["/register", "/admissions/register"],
  ["/registration", "/admissions/register"],
  ["/apply", "/admissions/register"],
  ["/boarding", "/boarding/full"],
  ["/boarding/full-boarding", "/boarding/full"],
  ["/boarding/day-boarding", "/boarding/day"],
  ["/programmes", "/programmes/the-atelier"],
  ["/facilities", "/campus/amenities"],
  ["/facilities/:slug", "/campus/:slug"],
  ["/campus", "/campus/amenities"],
  ["/sports", "/campus/sports"],
  ["/careers/jobs", "/careers/vacancies"],
  ["/careers/work-with-us", "/careers"],
  ["/jobs", "/careers/vacancies"],
  ["/contact-us", "/contact"],
  ["/campus-tour", "/book-a-tour"],
  ["/book-tour", "/book-a-tour"],
  ["/tour", "/virtual-tour"],
  ["/360", "/virtual-tour"],
  ["/news", "/blog"],
  ["/downloads", "/resources"],
  ["/privacy-policy", "/privacy"],
  ["/terms-and-conditions", "/terms"],
];

export const redirects: Redirect[] = map.map(([source, destination]) => ({
  source,
  destination,
  statusCode: 301,
}));
