import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type Slot = {
  slot: string;
  alt: string;
  credit: { photographer: string; source: string; url: string } | null;
};

/** Writes docs/CREDITS.md from the image manifest. Also run automatically by fetch-images. */
export function writeCredits(slots: Slot[]) {
  const stock = slots.filter((s) => s.credit && s.credit.source !== "Generated");
  const generated = slots.filter((s) => !s.credit || s.credit.source === "Generated");
  const lines = [
    "# Image credits",
    "",
    "Generated from `content/images.manifest.json` by `pnpm credits` (also run by `pnpm images:fetch`). The same list is rendered at `/credits`.",
    "",
    "Stock photos come only from Unsplash and Pexels via their official APIs, under their respective free licences, downloaded once and served locally.",
    "No image shows a real school's pupils, buildings or branding. All people named on the site are fictional.",
    "",
    "## Stock photographs",
    "",
    stock.length
      ? "| Slot | Description | Photographer | Source |\n|---|---|---|---|"
      : "_None yet — every slot currently uses a generated placeholder._",
    ...stock.map(
      (s) =>
        `| \`${s.slot}\` | ${s.alt} | [${s.credit!.photographer}](${s.credit!.url}) | ${s.credit!.source} |`,
    ),
    "",
    "## Generated artwork",
    "",
    `${generated.length} slots use original artwork generated by \`scripts/placeholders.ts\` (illustrated portraits, panoramas, map and any slot without a photo yet):`,
    "",
    generated.map((s) => `\`${s.slot}\``).join(", "),
    "",
    "## Fonts",
    "",
    "* Fraunces — SIL Open Font License 1.1 (Undercase Type), via Fontsource",
    "* Hanken Grotesk — SIL Open Font License 1.1 (Hanken Design Co.), via Fontsource",
    "",
  ];
  writeFileSync(path.join(process.cwd(), "docs/CREDITS.md"), lines.join("\n"));
}

if (process.argv[1]?.endsWith("build-credits.ts")) {
  const m = JSON.parse(readFileSync(path.join(process.cwd(), "content/images.manifest.json"), "utf8")) as {
    slots: Slot[];
  };
  writeCredits(m.slots);
  console.log("docs/CREDITS.md written");
}
