import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import { school } from "@/config/school";

export type SchoolEmailProps = {
  preview: string;
  heading: string;
  paragraphs: string[];
  facts?: [string, string][];
  cta?: { label: string; href: string };
  footnote?: string;
};

const colors = {
  plum: "#3d1d38",
  ink: "#231a21",
  muted: "#6b5a66",
  paper: "#fbf7f0",
  line: "#e7ddd0",
  gold: "#d9962b",
};

/** One branded React Email layout used by every transactional template. */
export function SchoolEmail({ preview, heading, paragraphs, facts, cta, footnote }: SchoolEmailProps) {
  return (
    <Html lang="en">
      <Head />
      <Preview>{preview}</Preview>
      <Body
        style={{
          backgroundColor: colors.paper,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: colors.ink,
          margin: 0,
        }}
      >
        <Container style={{ maxWidth: 560, margin: "0 auto", padding: "32px 24px" }}>
          <Text
            style={{
              fontFamily: "Georgia, serif",
              fontSize: 20,
              color: colors.plum,
              margin: 0,
              letterSpacing: 0.5,
            }}
          >
            {school.name}
          </Text>
          <Hr style={{ borderColor: colors.gold, borderWidth: 2, width: 40, margin: "12px 0 24px" }} />
          <Heading
            as="h1"
            style={{
              fontFamily: "Georgia, serif",
              fontSize: 26,
              fontWeight: 400,
              color: colors.plum,
              margin: "0 0 16px",
            }}
          >
            {heading}
          </Heading>
          {paragraphs.map((p, i) => (
            <Text key={i} style={{ fontSize: 15, lineHeight: "24px", margin: "0 0 14px" }}>
              {p}
            </Text>
          ))}
          {facts && facts.length > 0 && (
            <Section
              style={{
                backgroundColor: "#ffffff",
                border: `1px solid ${colors.line}`,
                borderRadius: 8,
                padding: "12px 16px",
                margin: "8px 0 20px",
              }}
            >
              {facts.map(([label, value]) => (
                <Text key={label} style={{ fontSize: 14, margin: "6px 0" }}>
                  <span style={{ color: colors.muted }}>{label}: </span>
                  <strong>{value}</strong>
                </Text>
              ))}
            </Section>
          )}
          {cta && (
            <Button
              href={cta.href}
              style={{
                backgroundColor: colors.plum,
                color: "#ffffff",
                padding: "12px 20px",
                borderRadius: 6,
                fontSize: 15,
              }}
            >
              {cta.label}
            </Button>
          )}
          <Hr style={{ borderColor: colors.line, margin: "32px 0 16px" }} />
          <Text style={{ fontSize: 12, color: colors.muted, lineHeight: "18px" }}>
            {footnote ??
              `${school.name} · ${school.contact.address.slice(1).join(", ")} · ${school.contact.phone}`}
            <br />
            Sample build — this message was generated by a demo system and was not sent to a real person.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
